name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Lint Javascript
      run: npm run lint
    - name: Lint Markdown
      run: npm run lint-md
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
        NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm run test:ci
    - name: Codecov
      uses: codecov/codecov-action@v1.0.10
      with:
        name: Mintel.me
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
