name: Lighthouse Mobile

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: '*/180 * * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v3
        with:
          runs: 1
          configPath: '.github/lighthouse/mobile.json'
          uploadArtifacts: true