name: Security

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: audit

jobs:
  audit:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Audit
        run: yarn audit